# Use postgres/example user/password credentials
version: '3.1'

services:
  api:
    build: ./back-end/.
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=mydb
      - DB_PORT=5432
      - DB_DIALECT=postgres
    volumes:
      - ./back-end:/usr/src/app 

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:      
      - ./back-end/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - db  
    depends_on:
      - db
    